INSERT INTO accounts (account_id, first_name, last_name) VALUES (2344, 'Tommy', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (2233, 'Barry', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (8766, 'Sally', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (2345, 'Jerry', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (2346, 'Ollie', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (2347, 'Tara', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (2348, 'Tammy', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (2349, 'Simon', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (2350, 'Colin', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (2351, 'Gladys', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (2352, 'Greg', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (2353, 'Tony', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (2355, 'Arthur', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (2356, 'Craig', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (6776, 'Laura', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (4534, 'JOSH', 'TEST');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (1234, 'Freya', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (1239, 'Noddy', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (1240, 'Archie', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (1241, 'Lara', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (1242, 'Tim', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (1243, 'Graham', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (1244, 'Tony', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (1245, 'Neville', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (1246, 'Jo', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (1247, 'Jim', 'Test');
INSERT INTO accounts (account_id, first_name, last_name) VALUES (1248, 'Pam', 'Test');

INSERT INTO meter_readings (id, account_id, submitted_at, value) VALUES (DEFAULT, 123, '2021-12-11 22:16:15.000000', '12312');
INSERT INTO meter_readings (id, account_id, submitted_at, value) VALUES (DEFAULT, 1234, '2021-12-11 22:16:15.000000', '42321');